### PR TITLE
feat(push): Add option to send a self-test

### LINKED ISSUE #1206: trigger "notification:test-push" via mobile apps (to self test push notifications)
It should be possible to trigger

`sudo -u www-data php /var/www/yourinstance/occ notification:test-push --talk youruser`

via API, so the mobile apps could have a "Test Notifications" button in the settings-view.

That notification should be catched on mobile clients and they show a success dialog.
If notification is not received within x seconds, show a dialog with the link to the troubleshooting checklist etc.

With this every user could check that pushproxy is working or not and it can be narrowed down why a notifications is not shown..
If possible, also give feedback to the mobile clients that the "notification:test-push" command was successfully executed on server...

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #1206 

---

grafik

### CODE REVIEW

**Review by Ivansss — APPROVED** [review]
Tested and work 👍

**Comment by SystemKeeper** [comment]
Should we rate limit that endpoint?

**Review by miaulalala — COMMENTED** [review]
Nice! But I agree with @SystemKeeper

**Comment by nickvergessen** [comment]
Had discussed earlier already, that there are many other points we would need to ratelimit to avoid a problem here (e.g. create a public conversation and mention yourself, create a public share, set activity to push on upload and bombard yourself).

And at the same time, we might want to have a temporary high frequency here anyway. I would only imagine something like 60 per hour?

**Pull request merged**
