### PR TITLE
support using notify_push to get push notifications

### PR DESCRIPTION
**Pull request by icewind1991**
When [`notify_push`](https://github.com/icewind1991/notify_push) is setup on the server, use it's websocket to get push updates for notifications, infrequent polling is still enabled as a fallback in case the push misses something.

This both lowers the server load by reducing the polling frequency and makes notifications realtime

### CODE REVIEW

**Comment by nickvergessen** [comment]
I can't get the binary running:
```
NEXTCLOUD_URL=https://nextcloud21.local/ PORT=8086 DATABASE_URL=mysql://oc_admin:…@localhost:3306/nextcloud21 REDIS_URL=redis://localhost:6379 ./notify_push
Error: 
   0: Failed to connect to Nextcloud database
   1: error with configuration: invalid port number
   2: invalid port number

Location:
   /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/eyre-0.6.3/src/context.rs:25

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

Also tried with IP and without port and both of that, but the result is always the same.

**Review by rullzer — APPROVED** [review]
Works for me on mariadb :)
:rocket:

**Comment by rullzer** [comment]
However this needs a rebase I think

**Comment by rullzer** [comment]
> However this needs a rebase I think

Done still works here.

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
