### PR TITLE
Icon support

### LINKED ISSUE #25: Support icons in notifications
@nickvergessen as we talked about. When there are more notifications, they should be able to show icons. In the beginning it could simply be the app icon, or for example the share icon for approving shares or federated shares.

(As said, the web notifications API also supports icons – see our usage in the Mail app – so it shouldn’t be an issue.)

### PR DESCRIPTION
**Pull request by nickvergessen**
bildschirmfoto vom 2016-10-10 16-02-39

Server for testing: master from sunday or later.
App for testing: https://github.com/nextcloud/announcementcenter/pull/43
Fix #25 

@MorrisJobke @jancborchardt

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Unit tests fail ;)

**Comment by nickvergessen** [comment]
Fixed

**Comment by jancborchardt** [comment]
I couldn’t get the announcementcenter + notifications app to create a notification … what could i have missed? Like do I need to compile, or set some settings or permissions?

(The layout needs to be fixed a bit, making the text always flush and the icon on the left – not having the text below the icon.)

**Comment by nickvergessen** [comment]
You need to run cron.php and be a different user then the poster

**Comment by nickvergessen** [comment]
Merging so I can continue with other work

**Pull request merged**
