### PR TITLE
Switch to escape-html

### PR DESCRIPTION
**Pull request by rullzer**
Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by rullzer** [comment]
It just doesn't convert `'` and `"` to the counter parts in escapeHTML... but I don't think that is an issue here

**Comment by rullzer** [comment]
Let me actually switch to escape-html as it is much smaller and does the same

**Comment by rullzer** [comment]
Done :)

**Comment by ChristophWurst** [comment]
https://github.com/search?l=JavaScript&q=org%3Anextcloud+escapeHtml&type=Code :)

**Comment by nickvergessen** [comment]
Whats the issue with the old method? it's being removed?

**Comment by rullzer** [comment]
> Whats the issue with the old method? it's being removed?

Yep deprecated.

**Pull request merged**
