### PR TITLE
fix: separate creation of browser notifications and sounds from Vue rendering

### PR DESCRIPTION
**Pull request by Antreesy**
### ☑️ Resolves

* Ref #1946
  * First attempt to solve missing browser notifications
  * Method is extracted to the separated file for reuse
  * Usage is moved from children component's lifecycle to the app root
  * Now works from inactive tab / minimized window

### 🖼️ Screenshots / Screencasts

No visual changes

### 🚧 Tasks

- [ ] check Web Worker - doesn't have access to window, OC, and other global variables, requires webpack change
- [x] check active/inactive state
- [ ] check frozen/ discarded states for suspended tabs

### 🏁 Checklist

- [ ] 🌏 Tested with Chrome, Firefox and Safari or should not be risky to browser differences
- [ ] 🖥️ Tested with Desktop client or should not be risky for it

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]
🐘

**Review by nickvergessen — APPROVED** [review]
Still plays sound in normal tabs and inactive tabs with Firefox.
Couldn't test the chrome suspension thou

**Review by ShGKme — APPROVED** [review]
Looks good code wise.

Testing results:

State | Before | After | Notes
---|---|---|---
hidden | ✅ shows notification | ✅ shows notification | -
frozen | ? | ? | *hard to test without waiting for a long time, chrome://discards has no "freeze" option*
discarded | ❌ no notification | ❌ no notification | *only solvable via worker*

**Pull request merged**
