### PR TITLE
Play a sound on notifications

### LINKED ISSUE #116: Sound on talk notifications
https://github.com/nextcloud/spreed/issues/627

### LINKED ISSUE #127: Sound on federated share request
I’d like there to be a sound for incoming *remote* federated share requests that arrive as a notification, awaiting my approval.  #116 is similar, but for a different app.

Edit: it might also make sense to play a sound for the sender of the remote share if it is approved/rejected

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Replace audio files with a notification like sound file

Assigning jan for "after vacation" since he wants to look whether the purism sound file is free/open source enough.

Fix #116 
Fix #127

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> Assigning jan for "after vacation" since he wants to look whether the purism sound file is free/open source enough.

The results are here: https://puri.sm/posts/librem5-ringtone-contest-winners/

**Comment by nickvergessen** [comment]
Thanks, added.

**Comment by MorrisJobke** [comment]
> Thanks, added.

I still don't know which license they have :/

**Comment by nickvergessen** [comment]
I guess we need to add the license somewhere in the readme or a shipped file?

**Comment by nickvergessen** [comment]
https://puri.sm/shop/librem-5/

> Please submit your free format sound clips via email to info@puri.sm with the subject “Ringtone Contest submission”, please provide the files under a [free cultural work license](https://en.wikipedia.org/wiki/Definition_of_Free_Cultural_Works), please name the files or reference the file names to the categories mentioned above. (e.g. purism-librem-5_email-at-domain_power-on.flac ).

**Comment by jancborchardt** [comment]
Reached out to the sound designer: https://twitter.com/jancborchardt/status/973602988223844352

The other sounds by feandesign are at https://soundcloud.com/feandesign/sets/librem-5-sounds and they are all really good, if we for example ever need the »Text message« blip for shorter notifications.

**Comment by jancborchardt** [comment]
The designer confirmed they are licensed under CC0: https://twitter.com/feandesign/status/1004095975265271810 – but let’s credit them in a readme at least. :)

**Comment by nickvergessen** [comment]
Now also includes the "email notification" sound for all other interactive notifications.

**Comment by jancborchardt** [comment]
Seems good to me. The permissions are all handled by the browser, so we don’t need to have an additional setting for "Enable sound" (checked by default), do we?

**Comment by nickvergessen** [comment]
Well permissions are only needed for the notification, but if you want that but no annoying sound... We could have 🔇 in the top corner of the dropdown?

**Comment by MorrisJobke** [comment]
Chrome and Safari both block auto playback if not caused by user interaction:

Chrome:

```
Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
```

Safari:

```
Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
```

**Comment by nickvergessen** [comment]
Okay, so do we want it for FF users or not at all?

**Comment by MorrisJobke** [comment]
> Okay, so do we want it for FF users or not at all?

I would then not add it. Because it is likely that FF will also block it sooner or later.

**Comment by honzapatCZ** [comment]
Facebook is able to do it while we cant? Couldnt it be like the user has to interact with the web page for some time and then it works?

**Comment by thecyberd3m0n** [comment]
can you just use webaudio? I missed many calls from Talk just because there is no sound...

https://www.npmjs.com/package/webaudio

**Comment by nickvergessen** [comment]
@honzapatCZ see https://github.com/nextcloud/notifications/issues/116#issuecomment-777279834

**Pull request closed without merging**
