### PR TITLE
Sound on notifications

### LINKED ISSUE #116: Sound on talk notifications
https://github.com/nextcloud/spreed/issues/627

### LINKED ISSUE #127: Sound on federated share request
I’d like there to be a sound for incoming *remote* federated share requests that arrive as a notification, awaiting my approval.  #116 is similar, but for a different app.

Edit: it might also make sense to play a sound for the sender of the remote share if it is approved/rejected

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #116 
Fix #127
Fix nextcloud/spreed#3388
Fix nextcloud/spreed#4651

Ref nextcloud/spreed#1444

### CODE REVIEW

**Comment by nickvergessen** [comment]
Questions for @jancborchardt @nimishavijay 

- [ ] Should there be a setting in notifications if sound should be played
- [ ] Should we also add a generic "bing" for other notifications (with an option)
- [ ] Should this be opt-out or opt-in (I guess opt-out?)

**Review by marcoambrosini — APPROVED** [review]

**Comment by marcoambrosini** [comment]
let's get this in for testing purposes and iterate on the feature with new prs

**Comment by brendan-pike** [comment]
Fantastic guys.  May I also suggest a user option for recurring sounds, ie. if I have not checked the message then play the sound again in x seconds.

**Comment by alexbijma** [comment]
is this already available on desktop ? I thought i've seen it in some announcement but this issue doesn't seem to be solved yet. so little confused.

**Comment by morgannunan** [comment]
Yeah, I'm confused by this, too. Yes, you get an audible ringtone when someone's calling you, but you don't get an audible anything when someone sends you a chat. There have been all this claims flying around that it's impossible to play a sound without the user initiation an action in their browser, but this is obviously untrue because you get a ring when someone's calling you. And then there's this, which supposedly was added to NC 24 but it isn't. There's no sound notification for spreed chats.

**Comment by nickvergessen** [comment]
There is the option to get a sound when receiving any notification. That also applies for chat messages.

**Comment by burtonkent** [comment]
> There is the option to get a sound when receiving any notification. That also applies for chat messages.

If you mean  "Play sound when a new notification arrives" 
found under Administration > Notifications, it doesn't work for chat messages. Which is actually understandable, since it could drive people nuts. So no, there's no chat notifications, but it would be great if it was an option.

**Comment by morgannunan** [comment]
Yeah. There must be varying user experiences around this issue, because I see a disconnect between the issues and the requests on the forums, and some of the responses from developers. I'm on Chrome / Linux, and I just don't get notified reliably when there's a message in the chat.

I think this would be resolved if there was an option to always play a sound. I would tolerate a sound effect going off all the time, whether I was focused on the chat or not, all day, every day, if it meant I got my messages. As it stands, I miss messages constantly because Nextcloud has its own secret sauce to decide whether it thinks I've seen a message or not. Sometimes I get a browser-based notification with a sound. Sometimes, I get a system-integrated notification from the Nextcloud desktop, with no sound. Usually, I get nothing, or if I get something I don't see or hear it.

I'm sure you know that lots of people are raising this issue and saying they're desperate to get notifications. So even though this appears to have been addressed, in actuality it is a persistent, unresolved issue.

**Pull request merged**
