### PR TITLE
[stable10] Switch notification icon to dark if theming app is using bright colors 

### PR DESCRIPTION
**Pull request by juliushaertl**
backport of #9

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by nickvergessen** [comment]
Can this be merged @juliushaertl ?

**Comment by nickvergessen** [comment]
Okay, just tested, seems to work in the basics, but when changing the color on the fly (for the admin) it fails to switch icons,
but would rate this low, so merging

**Comment by juliushaertl** [comment]
@nickvergessen yes, should be ok.

Right, the preview for the icon isn't working, but this need some more time. I'm still not sure how to solve this.

**Comment by nickvergessen** [comment]
Thanks for the work!

**Pull request merged**
