### PR TITLE
fix: drop deprecated jquery functions

### PR DESCRIPTION
**Pull request by Antreesy**
- Ref #1447
- update eslint rules
- drop usage of jquery:
  - `this.$refs.icon` and `this.$refs.button` are not existing anymore in the code, so doesn't work either way
  - `$.Event('OCA.Notification.Action')` is removed from server code
  - `this.$parent._$el.fadeOut(OC.menuSpeed)` is superseded with Vue transition-group

### CODE REVIEW

**Comment by nickvergessen** [comment]
> $.Event('OCA.Notification.Action') is removed from server code

Any app could have listened to it.
So we should add it to the upgrade docs

**Comment by Antreesy** [comment]
> So we should add it to the upgrade docs

You meant here? https://docs.nextcloud.com/server/latest/admin_manual/release_notes/upgrade_to_31.html

**Pull request merged**
