### PR TITLE
Use notification main link if no parameter has a link

### PR DESCRIPTION
**Pull request by eneiluj**
Maybe I didn't get it but if main notification link and rich parameter links are mutually exclusive (to avoid nested links I guess), there is a mistake here :grin:.

If I indeed didn't get it, I can still testify: the main link is not used with a basic notification definition like:
``` php
$notification->setParsedSubject($subject)
    ->setLink($link)
    ->setIcon('blabla');
```

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
:+1: :elephant:

**Review by nickvergessen — APPROVED** [review]
Look right, but didn't test

**Comment by nickvergessen** [comment]
And yeah they should be mutual exclusive to avoid nesting.

**Pull request merged**
