### PR TITLE
fix screenshot

### PR DESCRIPTION
**Pull request by CorruptCommit**
The screenshot in admin-notifications.md is currently broken, so lets fix it.

### CODE REVIEW

**Comment by nickvergessen** [comment]
That is actually a wrong screenshot.
It should be a copy of this one:
https://github.com/nextcloud/admin_notifications/blob/master/docs/Screenshot.png

**Comment by CorruptCommit** [comment]
Hey @nickvergessen,

I was kinda wondering about that.  Requested change has been made.

**Comment by nickvergessen** [comment]
Thanks for your work. I decided to make a new screenshot all together which shows the actions as well. If you dont mind check it out at https://github.com/nextcloud/notifications/pull/551

**Comment by CorruptCommit** [comment]
At the end of the day, I wanted a working screenshot.  The new one looks great.

**Pull request closed without merging**
