### PR TITLE
Cannot unfold plain text notifications

### LINKED ISSUE #814: Can't see/expand whole notification
### Steps to reproduce
1. Use Nextcloud you dummy

### Expected behaviour
I should see whole notification or at least have a button to expand it.

### Actual behaviour
Notification is cut in half and can't be clicked.

### Server configuration
This is basically the snap version of Nextcloud.

**Operating system**:
Ubuntu Server

**Web server:**
Apache2

**Database:**
mysql 5.7.32

**PHP version:**
7.4.13

**Nextcloud version:** 20.0.2

**Where did you install Nextcloud from:**
snap

And I don't feel like filling all of that useless information from the issue template, the problem is simple and the installation has few days, so it's almost fresh install, you can basically check the snap configuration.

The problem:
image

I can't click on it or read the rest of the notification. That's all really there is to it. You advertise that as something which supports up to 4000 characters per notification...

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #814

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by rullzer** [comment]
so node is still not happy

**Comment by nickvergessen** [comment]
It is now

**Pull request merged**
