### PR TITLE
Fix header icon accessibility

### PR DESCRIPTION
**Pull request by jancborchardt**
- [x] Fix opening on enter when focused

Related server pull request: https://github.com/nextcloud/server/pull/10310 cc @nextcloud/accessibility :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
Ready to review together with the server pull request at https://github.com/nextcloud/server/pull/10310 :)

**Comment by jancborchardt** [comment]
Btw @tyrylu did I invite you to the Nextcloud Conference in Berli  already? :) There's travel & hotel support for contributors, apply soon! All infos at https://nextcloud.com/conf/

**Comment by tyrylu** [comment]
You in fact did not, however because of my visual impairments i would need to find very likely someone to travel with me and i am not aware of anyone i could talk into this. The possibility sounds wonderful and getting to the place from the Czech republic would be relatively easy, but some friend as a guide would be much appreciated, so currently i doubt my attendance. Are any video recordings planned?

**Comment by jospoortvliet** [comment]
@tyrylu we will have video recording for the talks, yes... I'm sorry, I can't tell you if there are others coming from CZ who could help you get to Berlin :disappointed:

**Comment by tyrylu** [comment]
Thank you.

**Comment by tyrylu** [comment]
We could, definitely. I don't have much friends who a. would be at least partially interested in this conference and b. have time, but i hope i can sort something out. And, of course, thank you.

**Pull request merged**
