### PR TITLE
Fix (visually) removing first notification when executing an action

### PR DESCRIPTION
**Pull request by danxuliu**
When an action is executed first [its element is faded out](https://github.com/nextcloud/notifications/blob/c2385d9ac82e8efe2ce06477785c3d213100314f/src/Components/Action.vue#L120) and then [the notification data is removed](https://github.com/nextcloud/notifications/blob/c2385d9ac82e8efe2ce06477785c3d213100314f/src/Components/Action.vue#L121), which removes the component as a whole. However, the index of the notification was not provided, so [the event that handles the "remove" event always removed the data of the first notification](https://github.com/nextcloud/notifications/blob/7ad8f72cb9d5ad310a39bb261de631f00741b9ae/src/NotificationsApp.vue#L292-L294). Due to this when the action was triggered in another notification the first notification was also (visually) removed (and only until the notifications were fetched again from the server).

## How to test

- Setup the recording server in Talk
- Start a call
- Start and stop (once it has started, do not cancel the start) a recording three times
- Once the three notifications about a recording being available are shown, share to the chat the oldest of the recordings (the notification at the bottom)

### Result with this pull request

The last notification is removed

### Result without this pull request

Both the first and the last notifications are removed. If you keep the notifications open long enough (so the notifications are fetched again) the first notification will appear again

### CODE REVIEW

**Comment by SystemKeeper** [comment]
So the fact that I was seeing this only with 2 tabs and the message 

> Deferring notification refresh from browser storage are notify_push event to give the last tab the chance to do it

was just a coincidence?

**Comment by danxuliu** [comment]
> So the fact that I was seeing this only with 2 tabs and the message
> 
> > Deferring notification refresh from browser storage are notify_push event to give the last tab the chance to do it
> 
> was just a coincidence?

I was intrigued by that as well :shrug: Maybe there is something else, but at least I was able to reproduce the issue with a single tab and the steps above.

**Review by SystemKeeper — APPROVED** [review]
I was unable to reproduce it the way you described in only one tab, but still this PR seems to fix the issue I was seeing.

Also it makes sense, because on dismissal the index is already there:

https://github.com/nextcloud/notifications/blob/9e4bfdcf04d3a17402f4b22166e1afd4fc7ff833/src/Components/Notification.vue#L329

**Review by Ivansss — APPROVED** [review]
Tested and works 👍

**Comment by nickvergessen** [comment]
I guess we backport till 25?

**Comment by danxuliu** [comment]
> I guess we backport till 25?

That was what I was counting on the backportbot to do. Of course it would have helped if I have called it... :facepalm:

**Comment by danxuliu** [comment]
Oh, the irony... I will manually do the backports then.

**Comment by nickvergessen** [comment]
Well compiled assets, so it's expected

**Pull request merged**
