### PR TITLE
Send a push message when a notification was deleted

### LINKED ISSUE #250: Notifications should vanish when they are acted upon
### Steps to reproduce
1. Get a notification about something like a comment on a file or a call in the Talk app
2. _Don’t_ use the notification, but go to the file on the web interface and read the comment there, or open the Talk Android app and participate in the call there.
3. Afterwards, the notification of the comment or the call is still shown in the web interface Notifications display (bell with red dot) and also the desktop client notifies you every startup of it.

### Expected behaviour
Things you were notified of but which have been acted upon should be removed from notifications. It shouldn’t be necessary to go through the notification for it to know it needs to be removed, nor should people need to remove the outdated notifications manually.

### Actual behaviour
Currently the notifications stay until you remove them manually.

### Server configuration
Current installation on cloud.nc

cc @nickvergessen this is what I mentioned earlier in Talk. https://github.com/nextcloud/desktop/issues/685 is slightly related but not the core of the issue, as the notifications also still show up in the web interface.

### LINKED ISSUE #285: Extending the public APIs
### `OCP\Notifications\*`
* Type hints and return type hints.

### `OCP\Notifications\IActions`
* Add action type to open a new browser tab/page with the link instead of a background request

### `OCP\Notifications\IManager`
* Don't use Closures for registration, but just the class name + automatic generation

### `OCP\Notifications\INotifiers`
* Add method to return a display name and an ASCI identifier
* Allow to easily mark a notification as processed from within parsing (special exception)

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #285 
Fix #250 

Server requirement: https://github.com/nextcloud/server/pull/15040

### CODE REVIEW

**Comment by nickvergessen** [comment]
@skjnldsv mind to help?
On master it seems that the Vue stuff is not working anymore. I can see `<!-- -->` being added to the DOM, but the app itself does nto show up anymore :(

**Comment by skjnldsv** [comment]
@nickvergessen what you see is not the notifications app, the script is not even on the page for me :)

**Comment by nickvergessen** [comment]
Did you checkout https://github.com/nextcloud/server/pull/15040 on the server too?

**Comment by skjnldsv** [comment]
@nickvergessen right, I did not.
The notification app is here for me, but indeed, I do not receive anything.
Capture d’écran_2019-04-16_14-32-23


The get requests return an empty response for notifications

**Comment by tobiasKaminsky** [comment]
When I remove a notification in web ui, I do receive this in android app:
```
app = null
id = null
nid = 343
subject = null
type = null
```

I can then succesfully remove associated notification 343 from status bar.
Is this intended that all values are null? I would have expected to have e.g. "type = REMOVAL"?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/notifications/pull/318/files#diff-1383a847921c5d9a7163f3de431d5165R301

there are new parameters `delete` and `delete-all`

Type and ID refer to an object, so abusing them is not a good idea.

**Comment by tobiasKaminsky** [comment]
> there are new parameters `delete` and `delete-all`

Ah, great.
When can delete-all be triggered?


> Type and ID refer to an object, so abusing them is not a good idea.

Never wanted to do this :-)

**Comment by tobiasKaminsky** [comment]
Automatically json unboxing has a problem with delete-all, can we change this to deleteAll?

**Comment by tobiasKaminsky** [comment]
Android part is in: https://github.com/nextcloud/android/pull/3969

**Comment by MorrisJobke** [comment]
@nickvergessen What is the status here? We are close to the beta 1. Should this go into 17 or 18?

**Comment by nickvergessen** [comment]
Still on track and planned for today+tomorrow

**Pull request merged**
