### PR TITLE
[stable10] Fix style of notification

### PR DESCRIPTION
**Pull request by schiessle**
backport of https://github.com/nextcloud/notifications/pull/10

### CODE REVIEW

**Comment by schiessle** [comment]
cc @MorrisJobke I created a backport of your PR

**Comment by MorrisJobke** [comment]
I also added https://github.com/nextcloud/notifications/pull/13 to this backport.

**Comment by MorrisJobke** [comment]
I tested this and the backport works fine 👍

**Comment by MorrisJobke** [comment]
@rullzer @Bugsbane @juliushaertl Do you mind to review this one? Thanks :)

**Comment by Bugsbane** [comment]
Looks good here. :+1:

**Pull request merged**
