### PR TITLE
Switch notification icon to dark if theming app is using bright colors

### PR DESCRIPTION
**Pull request by juliushaertl**
This PR adds support for bright colors when using the theming app.

Requires https://github.com/nextcloud/server/pull/819

Fixes notification icon in top left is white instead of black in https://github.com/nextcloud/server/issues/735

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Comment by schiessle** [comment]
:+1:

**Comment by schiessle** [comment]
@juliushaertl can you prepare a backport for stable10? Thanks!

**Comment by MorrisJobke** [comment]
@juliushaertl FYI: When the backport PR is opened we usually remove the backport-request label. Then we can more easily find the not yet backported PRs ;)

**Comment by juliushaertl** [comment]
@MorrisJobke Thanks for the hint. That makes sense :smile:

**Pull request merged**
