### PR TITLE
build: replace Terser plugin with Esbuild

### PR DESCRIPTION
**Pull request by Antreesy**
State | Before | After | Diff
-- | -- | -- | --
Size | 26.7 Mb | 31.8 Mb | 🔼 +19%
Time |  50 943 ms | 14 765 ms | 🔽 -71%

### CODE REVIEW

**Comment by ShGKme** [comment]
To make it faster, we can also get rid of Babel for transpiling. Or fully migrate to Vite. Should be simple for a small app.

**Comment by ShGKme** [comment]
And extract CSS

**Comment by Antreesy** [comment]
> Or fully migrate to Vite

Feel free to take over, while we are still in beta phase 😉

**Comment by nickvergessen** [comment]
Fine by me?

**Review by ShGKme — APPROVED** [review]

**Comment by Antreesy** [comment]
As it was introduced only in Nc30, closing in favor of #2002

**Pull request closed without merging**
