### PR TITLE
Still push notifications of twofactor_nextcloud_notification when in DND

### LINKED ISSUE #1353: Still push twofactor notifications even if DND is set
E.g. the twofactor_nextcloud_notifications app should still send and display notifications if possible.

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #1353

### CODE REVIEW

**Review by rullzer — APPROVED** [review]

**Comment by nickvergessen** [comment]
/backport 7a8a862d49869577bd4e807ec371775efa6069d4 to stable25

**Comment by nickvergessen** [comment]
/backport 7a8a862d49869577bd4e807ec371775efa6069d4 to stable24

**Comment by nickvergessen** [comment]
/backport 7a8a862d49869577bd4e807ec371775efa6069d4 to stable23

**Pull request merged**
