### PR TITLE
fix(settings): Delete settings when a user is deleted

### LINKED ISSUE #1572: [Bug]: After removing a user with occ, some of its related data remains in DB table `oc_notifications_settings`
Hello,

Using Nextcloud 26.0.2 ([Yunohost package](https://github.com/YunoHost-Apps/nextcloud_ynh), but it seems not to be limited to that very package), when deleting a user using `occ`, I notice that if most of that user data is deleted as expected, some do remains (neither particularly heavy nor sensitve data, but still...) in the following tables
- `oc_notifications_settings`
- `oc_addressbookchanges` - reported at [Nextcloud server's Github](https://github.com/nextcloud/server/issues/38680)
- `oc_jobs` - reported at [Nextcloud server's Github](https://github.com/nextcloud/server/issues/38680)
- `oc_storages` - reported at [Nextcloud server's Github](https://github.com/nextcloud/server/issues/38680)
- `oc_mail_tags` - reported at Nextcloud Mail app's forum

### Steps to reproduce
1. Create a user `testuser`
2. Associate an email account to it in Nextcloud Mail app (that may be an optional step)
3. Delete the user using `occ user:delete testuser`
4. Check mentioned  MySQL table to see whether data related to `testuser` still remain in there.  

### Expected behaviour
I guess all data related to the deleted user should be removed (or at least that there an option is provided to do so)

### Actual behaviour
A few references to `testuser` remains in the table `oc_notifications_settings` in particular (as far as  Nextcloud notifications app seems to be concerned)

### Server configuration

**Operating system**:
Debian Bulleye

**Web server:**
Nginx

**Database:**
MariaDB 10.5

**PHP version:**
8.1

**Nextcloud version:** (see Nextcloud admin page)
26.02

**Where did you install Nextcloud from:**
[Yunohost](https://github.com/YunoHost-Apps/nextcloud_ynh)

**Nextcloud configuration:**

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "mydomain.tld"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.6.1",
        "overwrite.cli.url": "https:\/\/mydomain.tld",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "updatechecker": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "integrity.check.disabled": true,
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "5555",
            "timeout": "0.0",
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "hashing_default_password": true,
        "localstorage.allowsymlinks": true,
        "simpleSignUpLink.shown": false,
        "logout_url": "https:\/\/mydomain.tld\/yunohost\/sso\/?action=logout",
        "maintenance": false,
        "loglevel": 2
    }
}

```

**Are you using an external user-backend, if yes which one:** LDAP & SSO

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #1572 

cc @oleole39 in case you want to review

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by oleole39** [comment]
> Fix #1572 
> cc @oleole39 in case you want to review

I confirm that after applying the fix manually, I can't find any entry related to to the test user in the database anymore as far as `oc_notifications` table is concerned.
 
Comparing with the result of a test performed before applying the fix, I actually I see that references to the same test user have also disappeared in other tables:
- `oc_circles_event`
- `oc_circles_member`
- `oc_ldap_group_members`

Could they be related to this that as well in some way (which would a good thing I believe)?


<details>
<summary>Here are for reference the remaining entries in the DB found after a new test:</summary>

```log
INSERT INTO `oc_addressbookchanges` VALUES (44,'LDAP:newtestuser2.vcf',44,2,1);
INSERT INTO `oc_addressbookchanges` VALUES (45,'LDAP:newtestuser2.vcf',45,2,2);
INSERT INTO `oc_addressbookchanges` VALUES (46,'LDAP:newtestuser2.vcf',46,2,3);
INSERT INTO `oc_filecache` VALUES (16331,2,'appdata_ocj3l4h9vi3l/identityproof/user-newtestuser2','38afde154d4485f20f0dbc16690cf7a1',62,'user-newtestuser2',2,1,0,1687352403,1687352403,0,0,'6492f4538f3b1',31,'');
INSERT INTO `oc_filecache` VALUES (16332,2,'appdata_ocj3l4h9vi3l/identityproof/user-newtestuser2/private','924817a9b098956cd775cef5b1dd4525',16331,'private',8,3,3588,1687352403,1687352403,0,0,'a55e87b61085404456b0df49f25d2635',27,'');
INSERT INTO `oc_filecache` VALUES (16333,2,'appdata_ocj3l4h9vi3l/identityproof/user-newtestuser2/public','c40e021382e9aefc0cbd5c223680f5eb',16331,'public',8,3,451,1687352403,1687352403,0,0,'5b172675fad7f0ecda119626479ac034',27,'');
INSERT INTO `oc_jobs` VALUES (393,'OCA\\Settings\\BackgroundJobs\\VerifyUserData','{\"verificationCode\":\"\",\"data\":\"newtestuser2@mydomain.tld\",\"type\":\"email\",\"uid\":\"newtestuser2\",\"try\":0,\"lastRun\":1687352103}',0,1>
INSERT INTO `oc_jobs` VALUES (407,'OCA\\Forms\\BackgroundJob\\UserDeletedJob','{\"owner_id\":\"newtestuser2\"}',0,1687353456,0,0,'52316aebaa1090836d3039285bd5ff04',1);
INSERT INTO `oc_jobs` VALUES (408,'OCA\\Polls\\Cron\\UserDeletedJob','{\"owner\":\"newtestuser2\"}',0,1687353456,0,0,'cbaa2f79d8164c0c2f4a8c7e942baae6',1);
INSERT INTO `oc_mail_tags` VALUES (37,'newtestuser2','$label1','Important','#FF7A66',1);
INSERT INTO `oc_mail_tags` VALUES (38,'newtestuser2','$label2','Travail','#31CC7C',1);
INSERT INTO `oc_mail_tags` VALUES (39,'newtestuser2','$label3','Personnel','#A85BF7',1);
INSERT INTO `oc_mail_tags` VALUES (40,'newtestuser2','$label4','À faire','#317CCC',1);
INSERT INTO `oc_mail_tags` VALUES (41,'newtestuser2','$label5','Plus tard','#B4A443',1);
INSERT INTO `oc_storages` VALUES (26,'local::/home/yunohost.multimedia/newtestuser2/',1,NULL);
```
</details>

**Comment by nickvergessen** [comment]
Stable25 in https://github.com/nextcloud/notifications/pull/1592

**Pull request merged**
