### PR TITLE
build: migrate from Webpack to Vite

### PR DESCRIPTION
**Pull request by ShGKme**
- Migrate from Webpack to Vite, including:
  - Using ESBuild
  - Extracting CSS

Metric | Before | After
---|---|---
Build time | 16s | 9s
main page size | 4 MB | 1.3 MB JS + 0.01 MB CSS
settings page size | 3.7 MB | 0.6 MB JS + 0.07 MB CSS
admin-settings page size | 3.6 MB | 0.5 MB JS + 0.04 MB CSS
total size | 6.4 MB | 1.4 MB JS + 0.12 MB CSS

### CODE REVIEW

**Comment by ShGKme** [comment]
Checking reuse

**Comment by nickvergessen** [comment]
> Checking reuse

Add `css/**.css` to https://github.com/nextcloud/notifications/blob/master/REUSE.toml#L15 ?

**Comment by ShGKme** [comment]
> > Checking reuse
> 
> Add `css/**.css` to https://github.com/nextcloud/notifications/blob/master/REUSE.toml#L15 ?

Not only

**Review by Antreesy — APPROVED** [review]
Smoke tested, works fine. Changes also look valid. Thanks!

**Pull request merged**
