### PR TITLE
Prevent focus of scrollable element on Firefox

### PR DESCRIPTION
**Pull request by artonge**
An element was focusable between the notification icon and the first dismiss button. It was not useful to keep it focusable, and it was creating a weird "gap" between the two buttons.

Screencast from 07-06-2022 16:24:05

### CODE REVIEW

**Review by Pytal — COMMENTED** [review]
On master I cannot reproduce the bug of focusing on the div between the notification icon and the dismiss button, reproduction steps?

**Comment by artonge** [comment]
> On master I cannot reproduce the bug of focusing on the div between the notification icon and the dismiss button, reproduction steps?

Hmm, strange, nothing specific:

- server on master
- notification on master
- ctrl+f5 to clear your cache
- then it should be reproducible

Can someone else try to reproduce ?

**Comment by artonge** [comment]
Apparently, Firefox focus scrollable elements. I added a comment to the code to explain the addition.

**Comment by nickvergessen** [comment]
But that is okay, no? So you can scroll the list when it's long?

**Comment by nickvergessen** [comment]
Maybe instead the container should then have the hover feedback added?

**Comment by nickvergessen** [comment]
But there were also major changes in the app in the meantime, so maybe at the time of reporting it always triggered and now only when scrolling.
I would to skip for now and wait for another feedback loop

**Pull request closed without merging**
