### PR TITLE
Add contacts popup to notifications

### PR DESCRIPTION
**Pull request by nickvergessen**
- [ ] Popup is hide

### Steps
1. Share a file with user2
2. As user2 mention `@user1` in a comment
3. As user1  open notifications dropdown

### CODE REVIEW

**Comment by georgehrke** [comment]
Hm. Caching issue on your side? 

files - nextcloud chromium today at 3 53 35 pm

**Comment by nickvergessen** [comment]
yes, looks like. however for me the window is cut off and I see a scroll bar (needs a short file name, so the notification itself is shorter then the popup:
> bildschirmfoto vom 2017-04-27 15-57-33

**Comment by georgehrke** [comment]
I think that's caused by https://github.com/nextcloud/notifications/blob/d623c3eaa786b1a43d2bd39bad66449f66fe133a/css/styles.css#L176

We probably don't want to remove that here though cc @jancborchardt 

The alternative is to append it to the body and position it using javascript. (which is somewhat of a pain, because you always have to reposition it when the user scrolls)

**Comment by nickvergessen** [comment]
Okay, then lets just merge it

**Pull request merged**
