### PR TITLE
Fix Notifications aria label

### LINKED ISSUE #603: Label for Notifications button reads "t('notifications', 'Notifications')"
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.

### Steps to reproduce
1. Open the NextCloud front page and log in.
2. Inspect the accessible name for the Notifications button with your favorite accessibility inspection tool.

### Expected behaviour
The name should be "Notifications", possibly followed by a number of unread notifications.

### Actual behaviour
The name reads `t('notifications', 'Notifications')`, looking like a malformed call to the localization mechanism.

NextCloud 17.1.

CC @nextcloud/accessibility

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #603

### CODE REVIEW

**Comment by skjnldsv** [comment]
Rah, I'm sick of not being able to backport compiled files ^^'

**Comment by kesselb** [comment]
Why are you so fast? ;)

**Comment by skjnldsv** [comment]
> Why are you so fast? ;)

I'm a bot. Boop deet toop

**Pull request merged**
