### PR TITLE
Group delete pushes with a delete-multiple for the talk clients as th…

### LINKED ISSUE #936: Combine and limit delete-notification pushes
Currently all mobile clients always receive all delete-pushes. iOS ignores silent background notifications if there are too many, so we plan to limit and combine them:
- [ ] Only send talk to talk apps and all others to the files app
- [ ] Combine the multiple deletes into 1 push, so instead of:
 ```php
			[
				'nid' => 13,
				'delete' => true,
			]
```
 ```php
			[
				'nid' => 42,
				'delete' => true,
			]
```
 ```php
			[
				'nid' => 23,
				'delete' => true,
			]
```

the Talk iOS app receives:
 ```php
			[
				'nids' => [13, 42, 23],
				'delete-multiple' => true,
			]
```

### PR DESCRIPTION
**Pull request by nickvergessen**
…ey receive a lot

- [x] https://github.com/nextcloud/talk-android/pull/1142 (sheduled for app release v12)
- [x] https://github.com/nextcloud/talk-ios/pull/953

Fix #936

### CODE REVIEW

**Comment by MorrisJobke** [comment]
🏓

**Comment by nickvergessen** [comment]
Not too urgent, we can move it to 23 once the milestone exists

**Comment by MorrisJobke** [comment]
Done.

**Comment by nickvergessen** [comment]
@Ivansss did you implement this in the meantime?

**Comment by Ivansss** [comment]
No, it is not implemented.

**Comment by SystemKeeper** [comment]
@nickvergessen Implemented in https://github.com/nextcloud/talk-ios/pull/953

**Comment by nickvergessen** [comment]
Okay, then let me add this back to my todo

**Comment by nickvergessen** [comment]
Too many changes and conflicts, started to redo it in https://github.com/nextcloud/notifications/pull/1429
Leaving this old PR here so I can compare the steps

**Pull request closed without merging**
