### PR TITLE
Also check responses of 400 errors and so delete unknown devices

### PR DESCRIPTION
**Pull request by nickvergessen**
So before this PR, we tried to act on 400 errors already, but I didn't know that they throw an exception on the `post()`, so instead of performing on the response body, we `continue;` after we logged an info … :hushed: 

This is of course not what was intended. Further more, since the notifications are grouped and the proxy had an error which would immediately bail out with a 400 when there was 1 unknown device, instead of sending the rest, 1 broken notification token was enough to not send any notification anymore. And since we never deleted the unknown device the instance didn't "heal" itself, but always broke like this.

### CODE REVIEW

**Review by Ivansss — APPROVED** [review]
Tested and works 👍

**Review by rullzer — APPROVED** [review]

**Comment by nickvergessen** [comment]
Stable18 in https://github.com/nextcloud/notifications/pull/761

**Pull request merged**
