### PR TITLE
"Dismiss all notifications" button

### LINKED ISSUE #105: Dismiss All Notifications
Hi, I'm requesting the ability to **Dismiss All Notifications** in bulk rather than individually dismissing each one by clicking on the top right corner.  [Linked from Issue #7403 in the server app; thanks!](https://github.com/nextcloud/server/issues/7403#issuecomment-352814656)
dismiss-all

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Add endpoint
  - [x] Add unit test
  - [x] Add integration test
- [x] Add UI

Fix #105

### CODE REVIEW

**Comment by nickvergessen** [comment]
@jancborchardt screenshot okay?

> bildschirmfoto von 2018-01-30 12-25-15

like with the single dismiss the icon+text gets opacity 1 + pointer cursor on hover

**Comment by nickvergessen** [comment]
Add integration and unit tests and the UI.

Ready to review 🎉

**Comment by MorrisJobke** [comment]
Somehow the label is not properly aligned in Safari:

bildschirmfoto 2018-02-02 um 12 31 26

Let me check if I can fix this.

**Comment by MorrisJobke** [comment]
But for now this is good to get in 👍

**Comment by MorrisJobke** [comment]
Maybe also add a little spinner once the button is pressed to give immediate feedback,

**Comment by nickvergessen** [comment]
> Maybe also add a little spinner once the button is pressed to give immediate feedback - or disable the button for that time.

Also for actions and the normal dismiss, so lets do that in a new issue.

**Comment by nickvergessen** [comment]
Rebased because of #114

**Pull request merged**
