### PR TITLE
increase the icon size to 20px

### PR DESCRIPTION
**Pull request by szaimen**
Fix part of https://github.com/nextcloud/server/issues/19906
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by nickvergessen** [comment]
Since it's SVGs just change the size of the displayed element?

**Comment by szaimen** [comment]
Hm... Since the svg gets loaded directly into the website, I thought it would be easier to just modify the asset directly. Also I am not sure where I would need to modify the size of the asset in the code. Pointers are welcome! :)
See 
image

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/notifications/blob/master/css/styles.scss#L4-L5

**Comment by szaimen** [comment]
Hm... adjusting that value doesn't seem to work in my testing. Maybe because the value is overwritten by some other css code...

**Comment by szaimen** [comment]
What works is this 5992e34

**Comment by szaimen** [comment]
I'll try that again.

**Comment by szaimen** [comment]
Superseded by https://github.com/nextcloud/notifications/pull/1036

**Pull request closed without merging**
